version: "3.9"
services:
  zenn:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
      - /workdir/node_modules
    command: ["npm", "run", "preview"]

