version: "3.9"
services:
  zenn:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    working_dir: /workdir
    user: "${UID}:${GID}"
    command: ["npm", "run", "preview"]
